[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
  "forge-std=lib/forge-std/src/",
  "solmate=lib/solmate/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@chainlink/=lib/chainlink-brownie-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config